### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by LYL1946734397** [keviner1/FFMEF#1]
Can you share the address of the paper?

**Comment by keviner1** [comment]
Thank you for your kind attention. We are pleased to announce that the paper has been uploaded and is now available for review.

**Comment by LYL1946734397** [comment]
Thank you so much for uploading your article and code, both are great! Hope to have the opportunity to communicate more in the future!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "keviner1/FFMEF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月17日(星期三) 下午2:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [keviner1/FFMEF] paper (Issue #1)





 
Thank you for your kind attention. We are pleased to announce that the paper has been uploaded and is now available for review.
